server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 111

  redis:
    host: localhost
    port: 6379
    database: 0
    password:


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: G:\abc\


#     发送邮件相关配置
mail:
  host: smtp.126.com # 此处使用的是126邮箱进行邮件发送
  username: xiaoyangsean@126.com # 发送邮件的账号（也就是本人账号）
  password: HSWWBNBRSXHCAIIS # 账号秘钥（注意不是密码！该秘钥在开启SMTP服务时会给出。）